Note: Html files(400.html,403.html,404.html,501.html,505.html) for displaying the error messages are to be downloaded and put 
in server directory(document-root) location along with the other server files before compiling the Server.java program.

Command for downloading server files of www.scu.edu/index.html to document-root location 
after moving to the document-root using cd command
>wget -r www.scu.edu/index.html 

Cut and paste all the files from www.scu.edu folder to document-root and delete the www.scu.edu folder.

Compile Instructions
1) Move to the directory containing the downloaded Server.java file using cd command. 
2) Execute the following commands from the terminal to compile and run the server. 
>javac Server.java
>java Server -document_root "/home/chitra/Desktop/webserver_files" -port 8888

